---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- CORE:
    - Traefik:
        icon: traefik.svg
        href: https://traefik.{{HOMEPAGE_VAR_DOMAINNAME_SERVER}}
        description: Reverse proxy
        # widget:
        #     type: traefik
        #     url: https://traefik:8080
    
    - Dozzle:
        icon: dozzle.svg
        href: https://dozzle.{{HOMEPAGE_VAR_DOMAINNAME_SERVER}}
        description: Real-time log viewer

    - Portainer:
        icon: portainer.svg
        href: https://portainer.{{HOMEPAGE_VAR_DOMAINNAME_SERVER}}
        description: Web UI docker container management
        widget:
            type: portainer
            url: https://portainer:9443
            env: 1
            key: {{HOMEPAGE_VAR_PORTAINER_API_KEY}}

- MEDIA:
    - Jellyfin:
        icon: jellyfin.svg
        href: https://jellyfin.{{HOMEPAGE_VAR_DOMAINNAME_SERVER}}
        description: Self-hosted media server
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          showEpisodeNumber: false # optional, defaults to false
          expandOneStreamToTwoRows: true # optional, defaults to true
    
    - Jellyseerr:
        icon: jellyseerr.svg
        href: https://jellyseerr.{{HOMEPAGE_VAR_DOMAINNAME_SERVER}}
        description: Media request management
        widget:
            type: jellyseerr
            url: http://jellyseerr:5055
            key: {{HOMEPAGE_VAR_JELLYSEERR_API_KEY}}

    - qBittorrent:
        icon: qbittorrent.svg
        href: https://qbitt.{{HOMEPAGE_VAR_DOMAINNAME_SERVER}}
        description: Torrent client
        widget:
          type: qbittorrent
          url: http://qbittorrent:8080
          username: {{HOMEPAGE_VAR_QBITT_USERNAME}}
          password: {{HOMEPAGE_VAR_QBITT_PW}}

    
    - Radarr:
        icon: radarr.svg
        href: https://radarr.{{HOMEPAGE_VAR_DOMAINNAME_SERVER}}
        description: Automated movie management
        widget:
            type: radarr
            url: http://radarr:7878
            key: {{HOMEPAGE_VAR_RADARR_API_KEY}}

    - Sonarr:
        icon: sonarr.svg
        href: https://sonarr.{{HOMEPAGE_VAR_DOMAINNAME_SERVER}}
        description: Automated series management
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: {{HOMEPAGE_VAR_SONARR_API_KEY}}
    
    - Prowlarr:
        icon: prowlarr.svg
        href: https://prowlarr.{{HOMEPAGE_VAR_DOMAINNAME_SERVER}}
        description: Indexer manager
        widget:
            type: prowlarr
            url: http://prowlarr:9696
            key: {{HOMEPAGE_VAR_PROWLARR_API_KEY}}
    
    - Bazarr:
        icon: bazarr.svg
        href: https://bazarr.{{HOMEPAGE_VAR_DOMAINNAME_SERVER}}
        description: Automated subtitles management
        widget:
            type: bazarr
            url: http://bazarr:6767
            key: {{HOMEPAGE_VAR_BAZARR_API_KEY}}
    
    - JDownloader2:
        icon: jdownloader2.png
        href: https://jdown.{{HOMEPAGE_VAR_DOMAINNAME_SERVER}}
        description: Download manager
        # widget:
        #     type: jdownloader
        #     client: jdownloader


- UTILITIES:
    - Uptime Kuma:
        icon: uptime-kuma.svg
        href: https://kuma.{{HOMEPAGE_VAR_DOMAINNAME_SERVER}}
        description: Self-hosted uptime monitoring

    - Scrutiny:
        icon: scrutiny.svg
        href: https://scrutiny.{{HOMEPAGE_VAR_DOMAINNAME_SERVER}}
        description: Hard-drive health monitoring
        widget:
            type: scrutiny
            url: http://scrutiny:8080

    - Speedtest Tracker:
        icon: speedtest-tracker-old.png
        href: https://speedtest.{{HOMEPAGE_VAR_DOMAINNAME_SERVER}}
        description: Speedtest monitoring
        widget:
            type: speedtest
            url: http://speedtest:80
    
    - Filebrowser:
        icon: filebrowser.svg
        href: https://filebrowser.{{HOMEPAGE_VAR_DOMAINNAME_SERVER}}
        description: Web file managing interface

    - Smokeping:
        icon: smokeping.png
        href: https://smokeping.{{HOMEPAGE_VAR_DOMAINNAME_SERVER}}
        description: Network latency monitoring


- MISC: 
    - Mealie:
        icon: mealie.svg
        href: https://mealie.{{HOMEPAGE_VAR_DOMAINNAME_SERVER}}
        description: Recipe manager
        widget:
          type: mealie
          url: http://mealie:9000
          key: {{HOMEPAGE_VAR_MEALIE_API_KEY}}

- GAME SERVERS:
    - Minecraft:
        icon: minecraft.svg
        description: Modded server
        widget:
          type: minecraft
          url: tcp://minecraft:25565
